[Variables]

;-------------------------------------------
; VARIABLES
;-------------------------------------------

MainColour=255,255,255
SecondaryColour=255,255,255
TertiaryColour=0,0,0
QuaternaryColour=255,255,255
QuinaryColour=255,255,255

Analogue=ue
Colour=u

;---------------------------------------------
; GALLERY
;---------------------------------------------

GalleryWidth=240
GalleryHeight=135
GallerySeconds=30
GalleryPath=C:\Users\Public\Pictures\Sample Pictures

;---------------------------------------------
; LAUNCHERS
;---------------------------------------------

Launcher1Text=Firefox
Launcher1Path=firefox.exe
Launcher1IconHidden=0
Launcher1IconPath=C:\Users\Joseph\Documents\Rainmeter\Skins\Amnio\@Resources\Images\Firefox.png
Launcher1IconTint=0,0,0,150

Launcher2Text=Photoshop
Launcher2Path=photoshop.exe
Launcher2IconHidden=0
Launcher2IconPath=C:\Users\Joseph\Documents\Rainmeter\Skins\Amnio\@Resources\Images\Photoshop.png
Launcher2IconTint=0,0,0,150

Launcher3Text=Word
Launcher3Path=winword.exe
Launcher3IconHidden=0
Launcher3IconPath=C:\Users\%UserName%\Documents\Rainmeter\Skins\Amnio\@Resources\Images\Word.png
Launcher3IconTint=0,0,0,150

Launcher4Text=Explorer
Launcher4Path=explorer.exe
Launcher4IconHidden=0
Launcher4IconPath=C:\Users\%UserName%\Documents\Rainmeter\Skins\Amnio\@Resources\Images\Explorer.png
Launcher4IconTint=0,0,0,150

;---------------------------------------------
; MUSIC
;---------------------------------------------

MusicSize=180
MusicPlayer=iTunes
MusicPlayerTitle=iTunes

;---------------------------------------------
; NETWORK
;---------------------------------------------

DownloadSize=20
DownloadFont=Regular
UploadSize=20
UploadFont=Regular

;---------------------------------------------
; NOTES
;---------------------------------------------

NotesWidth=220
NotesHeight=300
NotesTitle=Notes
NotesPath=C:\Users\Joseph\Documents\Rainmeter\Skins\Amnio\Notes\Notes.txt

;---------------------------------------------
; SYSTEM
;---------------------------------------------

CPUSize=20
CPUFont=Regular
PowerSize=20
PowerFont=Regular
PowerIconSize=60
RAMSize=20
RAMFont=Regular
HDD1Drive=C
HDD1Size=32
HDD1Font=Regular
HDD2Drive=E
HDD2Size=32
HDD2Font=Regular
HDD3Drive=F
HDD3Size=32
HDD3Font=Regular

;---------------------------------------------
; TASKBAR
;---------------------------------------------

TaskbarOrientation=0

TaskbarLauncher1Hidden=0
TaskbarLauncher1Name=Firefox
TaskbarLauncher1Path=firefox.exe
TaskbarLauncher2Hidden=0
TaskbarLauncher2Name=Photoshop
TaskbarLauncher2Path=photoshop.exe
TaskbarLauncher3Hidden=0
TaskbarLauncher3Name=Word
TaskbarLauncher3Path=winword.exe
TaskbarLauncher4Hidden=0
TaskbarLauncher4Name=Explorer
TaskbarLauncher4Path=explorer.exe
TaskbarLauncher5Hidden=0
TaskbarLauncher5Name=Google
TaskbarLauncher5Path=https://www.google.com/
TaskbarLauncher6Hidden=0
TaskbarLauncher6Name=DeviantART
TaskbarLauncher6Path=https://www.deviantart.com/
TaskbarLauncher7Hidden=0
TaskbarLauncher7Name=Youtube
TaskbarLauncher7Path=https://www.youtube.com/
TaskbarLauncher8Hidden=0
TaskbarLauncher8Name=Rainmeter
TaskbarLauncher8Path=http://rainmeter.net/

TaskbarBinHidden=0
TaskbarSystemHidden=0
TaskbarVolumeHidden=0
TaskbarPowerHidden=0
TaskbarTimeHidden=0

;---------------------------------------------
; TIME
;---------------------------------------------

AnalogueClockSize=512
AnalogueClockFaceShape=1

DateSize=24
DateFont=Regular

DigitalClockSize=72
DigitalClockFont=Light
DigitalClockLeadingZero=#
DigitalClockFormat=I

;---------------------------------------------
; VOLUME
;---------------------------------------------

VolumeWidth=180

;---------------------------------------------
; WEATHER
;---------------------------------------------

Unit=m
    ;f
WeatherCode=GIXX0001
