[Variables]
Total=9
LastOpen=3

Name1=Kerbal Space Program
Icon1=KSP.png
Dir1=steam://rungameid/220200
Background1=KSP.jpg

Name2=Subnautica
Icon2=subnautica.png
Dir2=steam://rungameid/264710
Background2=subnautica.jpg

Name3=Minecraft
Icon3=minecraft.png
Cover3=minecraft.png
Background3=minecraft.jpg
Dir3=C:\Program Files (x86)\Minecraft Launcher\MinecraftLauncher.exe

Name4=Just Cause 3
Icon4=JC3.png
Dir4=steam://rungameid/225540
Background4=JC3.jpg

Name5=Undertale
Icon5=undertale.png
Dir5=steam://rungameid/391540
Background5=undertale.png

Name6=Windlands
Icon6=windlands.png
Dir6=steam://rungameid/428370
Background6=windlands.jpg

Name7=Goat Simulator
Icon7=GoatSimulator.png
Dir7=steam://rungameid/265930
Background7=GoatSimulator.jpg

Name8=Scrap Mechanic
Icon8=ScrapMechanic.png
Dir8=steam://rungameid/387990
Background8=ScrapMechanic.png

Name9=Plague Inc: Evolved
Icon9=PlagueInc.png
Dir9=steam://rungameid/246620
Background9=PlagueInc.jpg
