[Variables]
Total=6
LastOpen=2

Name1=This PC
Icon1=PC.png
Cover1=PC.jpg
Dir1=shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

Name2=Chrome
Icon2=chrome.png
Cover2=chrome.jpg
Dir2=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

Name3=Photoshop
Icon3=ps.png
Cover3=ps.jpg
Dir3=C:\Program Files\Adobe\Adobe Photoshop CC 2019\Photoshop.exe

Name4=Discord
Icon4=discord.png
Cover4=discord.jpg
Dir4=C:\Users\omerk\AppData\Local\Discord\Update.exe --processStart Discord.exe

Name5=Photos
Icon5=Photo.png
Cover5=Photo.jpg
Background5=
Dir5=shell:appsFolder\Microsoft.Windows.Photos_8wekyb3d8bbwe!App

Name6=Settings
Icon6=setting.png
Cover6=setting.jpg
Background6=
Dir6=ms-settings: